# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pout < Formula
  desc ""
  homepage ""
  version "0.1.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lix-it/pout/releases/download/0.1.2/pout_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "44bd043f3f67622169e24a37a15260b4dce96e1c2f7e651f020f3e031b9c38d0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lix-it/pout/releases/download/0.1.2/pout_0.1.2_Darwin_arm64.tar.gz"
    sha256 "3b8223a7ecca93781e96f4525a2dbd70916a965550c4e7c8d9b861c0c9c4d23e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lix-it/pout/releases/download/0.1.2/pout_0.1.2_Linux_x86_64.tar.gz"
    sha256 "74e46d608458478083977785e846b41e6a2d4432c8263c08a2e4d47385d410e8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lix-it/pout/releases/download/0.1.2/pout_0.1.2_Linux_arm64.tar.gz"
    sha256 "c0b3412a30bb7b6a3ac62910202e47ee6adfad7cfbdab16715bfc641971e80e1"
  end

  def install
    bin.install "pout"
  end
end
