# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pout < Formula
  desc ""
  homepage ""
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lix-it/pout/releases/download/v0.1.1/pout_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "b2c523e1baa4bc8096160e3f9f151b9b809d780d2550f3be8cf77e4e5893a638"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lix-it/pout/releases/download/v0.1.1/pout_0.1.1_Darwin_arm64.tar.gz"
    sha256 "a7680c92f87c8d22a3cce8b6252225c8502199e263d5a86589af38e44b7ff0b4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lix-it/pout/releases/download/v0.1.1/pout_0.1.1_Linux_x86_64.tar.gz"
    sha256 "1f1404aa2c3949eb11439f89e4a8b530b05836fca917675e30ce35e0f2be4ec8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lix-it/pout/releases/download/v0.1.1/pout_0.1.1_Linux_arm64.tar.gz"
    sha256 "9dbc2744dfc33b7fb32a0716a5d76c24e58eea242e2ca011797764998439fbd4"
  end

  def install
    bin.install "pout"
  end
end
