# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pout < Formula
  desc ""
  homepage ""
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lix-it/pout/releases/download/v0.2.0/pout_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "330962c6499fe7e0a5912a7055ec0c3e5fbdb00517fcfc4deb69e83d83c5d7ab"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lix-it/pout/releases/download/v0.2.0/pout_0.2.0_Darwin_arm64.tar.gz"
    sha256 "6b48c3ad38de12b4eca40b8a58e84f62b7ef86054ba48e66b219ab3f7ead31c2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lix-it/pout/releases/download/v0.2.0/pout_0.2.0_Linux_x86_64.tar.gz"
    sha256 "8b0797f797e83a35942f924c85314ec31b6482b0c97b154395149c481aa62fae"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lix-it/pout/releases/download/v0.2.0/pout_0.2.0_Linux_arm64.tar.gz"
    sha256 "5123e8d1fb341df8d13a3529b424ae3fd27f27de37966cb08a8012cf7db90eca"
  end

  def install
    bin.install "pout"
  end
end
